### ISSUE TITLE
Автоматически генерировать скриншт для каждой страницы

### ISSUE THREAD

**Issue by nikolay-govorov** [nikolay-govorov/govorov.online#8]
Можно использовать https://github.com/vladocar/screenshoteer

**Comment by 4enki** [comment]
@nikolay-govorov, а подскажи, зачем ты хочешь генерировать скриншоты страниц? Для использования в `og`-разметке при шаринге страницы в соцсетях? Или есть не такие очевидные цели?

**Comment by nikolay-govorov** [comment]
Сходу, для og-разметки,но вообще хочу приспособить для тестирования
